```{r}
library(tidyverse)
```

```{r}
airquality=datasets::airquality
#shows solar radiation, wind, temperature and ozone concentration on each day of mai, june, july, august and september.
```

```{r}
airqualityC=airquality
airqualityC[,4]=((airqualityC[,4]-32)*(5/9))
plot(airqualityC[,4],type="l",xlab="month",ylab="temp in C°")
#assumption that temperature was originally given in fahrenheit
```
```{r}
library(ggplot2)
```

```{r}
ggplot(
    airqualityC,
    aes(x = seq(1:153), y = Solar.R)) +
  geom_line() +
  labs(x = "Time", y = "Solar.R") +
  theme_classic()
```

```{r}
airqualityC[,5] <- month.name[airqualityC[,5]]
```

```{r}
ggplot(airqualityC, aes(x= Solar.R, y=..density..)) +
  geom_histogram(fill="grey70", color = "black") + geom_density(color = "red")+labs(x="Sonnenstrahlung",y="Häufigkeitsdichte")
```
```{r}
#regression line for Temp and Solar.R

#first create a table with only 2 variables
airqualityCT_R=airqualityC[,2:4]
airqualityCT_R$Wind=NULL

#with the lm() function the intersect and slope can be found
lm(airqualityCT_R)
cor.test(airqualityCT_R[,1],airqualityCT_R[,2])
```
```{r}
plot(airqualityC[,4],airqualityC[,2],type="p",ylab="Sonnenstrahlung",xlab="Temperatur")
abline(a=61.743,b=4.847)
```

```{r}
ggplot(boxplot(airqualityC[,3]))
```

